use serde::{Deserialize, Serialize};
use std::{fs, path::Path};
use thiserror::Error;

#[derive(Debug, Error)]
pub enum ProjectBuilderError {
    #[error("build requires explicit user confirmation")]
    NotConfirmed,
    #[error("filesystem error: {0}")]
    Io(#[from] std::io::Error),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PlanArtifact { pub id: String, pub title: String, pub stack: Vec<String>, pub steps: Vec<String>, pub project_tree: String, pub status: String, pub edited: bool }

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BuildResult { pub root_path: String, pub files: Vec<String>, pub skipped: bool, pub message: String }

pub fn build_project(artifact: &PlanArtifact, confirmed: bool, base_dir: &Path) -> Result<BuildResult, ProjectBuilderError> {
    if !confirmed { return Err(ProjectBuilderError::NotConfirmed); }
    let root = base_dir.join(slugify(&artifact.title));
    let files = vec!["README.md", "docs/plan.md", "src/.gitkeep", "tests/.gitkeep"];
    fs::create_dir_all(root.join("docs"))?;
    fs::create_dir_all(root.join("src"))?;
    fs::create_dir_all(root.join("tests"))?;
    fs::write(root.join("README.md"), format!("# {}\n\nGenerated by Neurogate Project Builder.\n", artifact.title))?;
    fs::write(root.join("docs/plan.md"), format!("# План\n\n## Стек\n{}\n\n## Шаги\n{}\n", artifact.stack.iter().map(|item| format!("- {item}")).collect::<Vec<_>>().join("\n"), artifact.steps.iter().map(|item| format!("- {item}")).collect::<Vec<_>>().join("\n")))?;
    fs::write(root.join("src/.gitkeep"), "")?;
    fs::write(root.join("tests/.gitkeep"), "")?;
    Ok(BuildResult { root_path: root.display().to_string(), files: files.into_iter().map(String::from).collect(), skipped: false, message: "Проект записан на диск после подтверждения пользователя".into() })
}

fn slugify(value: &str) -> String {
    value.chars().map(|ch| if ch.is_ascii_alphanumeric() { ch.to_ascii_lowercase() } else { '-' }).collect::<String>().split('-').filter(|part| !part.is_empty()).collect::<Vec<_>>().join("-")
}
