use serde::{Deserialize, Serialize};
use std::{
    fs,
    path::{Path, PathBuf},
};
use thiserror::Error;
use time::{format_description::well_known::Rfc3339, OffsetDateTime};

#[derive(Debug, Error)]
pub enum ProjectBuilderError {
    #[error("build requires explicit user confirmation")]
    NotConfirmed,
    #[error("workspace path is empty")]
    EmptyWorkspacePath,
    #[error("filesystem error: {0}")]
    Io(#[from] std::io::Error),
    #[error("time format error: {0}")]
    TimeFormat(#[from] time::error::Format),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PlanArtifact {
    pub id: String,
    pub title: String,
    pub stack: Vec<String>,
    pub steps: Vec<String>,
    pub project_tree: String,
    pub status: String,
    pub edited: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BuildResult {
    pub phase: String,
    pub root_path: String,
    pub files: Vec<String>,
    pub skipped: bool,
    pub message: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WorkspaceInitResult {
    pub root_path: String,
    pub files: Vec<String>,
    pub created_files: Vec<String>,
    pub existing_files: Vec<String>,
    pub message: String,
}

pub fn build_project(
    artifact: &PlanArtifact,
    confirmed: bool,
    base_dir: &Path,
    workspace_path: Option<&Path>,
) -> Result<BuildResult, ProjectBuilderError> {
    if !confirmed {
        return Err(ProjectBuilderError::NotConfirmed);
    }

    let root = workspace_path
        .map(PathBuf::from)
        .unwrap_or_else(|| base_dir.join(slugify(&artifact.title)));
    if root.as_os_str().is_empty() {
        return Err(ProjectBuilderError::EmptyWorkspacePath);
    }

    let init = init_workspace(&root)?;
    let mut files = init.files;

    let mut readme_created_files = Vec::new();
    write_if_missing(
        &root,
        "README.md",
        &format!(
            "# {}\n\nGenerated by RamTeamAi Project Builder.\n\nРабочие файлы системы:\n\n- `MEMORY.md` — память проекта.\n- `PLAN.md` — текущий план.\n- `docs/plan.md` — build-снимок плана.\n",
            artifact.title
        ),
        &mut files,
        &mut readme_created_files,
    )?;

    fs::create_dir_all(root.join("docs"))?;
    fs::write(root.join("docs/plan.md"), render_plan(artifact))?;
    if !files.iter().any(|file| file == "docs/plan.md") {
        files.push("docs/plan.md".into());
    }

    Ok(BuildResult {
        phase: "scaffold".into(),
        root_path: root.display().to_string(),
        files,
        skipped: false,
        message: "Проект записан в выбранную рабочую папку. Файлы MEMORY.md и PLAN.md сохранены без перезаписи.".into(),
    })
}

pub fn init_workspace(root_path: &Path) -> Result<WorkspaceInitResult, ProjectBuilderError> {
    if root_path.as_os_str().is_empty() {
        return Err(ProjectBuilderError::EmptyWorkspacePath);
    }

    fs::create_dir_all(root_path)?;

    let mut files = Vec::new();
    let mut created_files = Vec::new();
    let mut existing_files = Vec::new();
    let created_at = OffsetDateTime::now_utc().format(&Rfc3339)?;

    for dir in ["docs", "src", "tests", "assets"] {
        fs::create_dir_all(root_path.join(dir))?;
        write_if_missing(root_path, &format!("{dir}/.gitkeep"), "", &mut files, &mut created_files)?;
    }

    write_if_missing(root_path, "MEMORY.md", &memory_template(&created_at), &mut files, &mut created_files)?;
    write_if_missing(root_path, "PLAN.md", &plan_template(&created_at), &mut files, &mut created_files)?;

    existing_files.extend(
        files
            .iter()
            .filter(|file| !created_files.contains(file))
            .cloned(),
    );

    Ok(WorkspaceInitResult {
        root_path: root_path.display().to_string(),
        files,
        created_files,
        existing_files,
        message: "Рабочая папка инициализирована: созданы структура, MEMORY.md и PLAN.md без перезаписи существующих файлов.".into(),
    })
}

fn write_if_missing(
    root: &Path,
    relative_path: &str,
    content: &str,
    files: &mut Vec<String>,
    created_files: &mut Vec<String>,
) -> Result<(), ProjectBuilderError> {
    let path = root.join(relative_path);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    if path.exists() {
        if !files.iter().any(|file| file == relative_path) {
            files.push(relative_path.into());
        }
        return Ok(());
    }
    fs::write(path, content)?;
    files.push(relative_path.into());
    created_files.push(relative_path.into());
    Ok(())
}

fn render_plan(artifact: &PlanArtifact) -> String {
    format!(
        "# План\n\n## Стек\n{}\n\n## Шаги\n{}\n",
        artifact
            .stack
            .iter()
            .map(|item| format!("- {item}"))
            .collect::<Vec<_>>()
            .join("\n"),
        artifact
            .steps
            .iter()
            .map(|item| format!("- {item}"))
            .collect::<Vec<_>>()
            .join("\n")
    )
}

fn memory_template(created_at: &str) -> String {
    format!(
        "# Memory\n\nПамять проекта для RamTeamAi.\n\n## Контекст\n- Цель проекта:\n- Важные решения:\n- Ограничения:\n- Ссылки и источники:\n\n## Журнал\n- {created_at}: рабочая папка инициализирована командой init.\n"
    )
}

fn plan_template(created_at: &str) -> String {
    format!(
        "# Plan\n\nПлан проекта для RamTeamAi.\n\n## Цель\n- \n\n## Задачи\n- [ ] Описать задачу\n- [ ] Собрать контекст\n- [ ] Реализовать решение\n- [ ] Проверить результат\n\n## Следующий шаг\n- \n\n---\nСоздано: {created_at}\n"
    )
}

fn slugify(value: &str) -> String {
    value
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() {
                ch.to_ascii_lowercase()
            } else {
                '-'
            }
        })
        .collect::<String>()
        .split('-')
        .filter(|part| !part.is_empty())
        .collect::<Vec<_>>()
        .join("-")
}
